### ISSUE TITLE
wrong default ftp credentials

### ISSUE THREAD

**Issue by vzrandom** [andresoviedo/google-drive-ftp-adapter#10]
Hi,

I think that on your last commit you accidentally left wrong default credentials:

now is:
ftp.user=pep
ftp.pass=patata

according to documentation it should be:
ftp.user=user
ftp.pass=user

Everything is fine, it's just confusing for the new users that are testing your software 

Great job by the way, keep it up

**Comment by andresoviedo** [comment]
Thank you body!
& merry christhmast!
;)
