### ISSUE TITLE
I want to change user ans pass

### ISSUE THREAD

**Issue by Androdiver** [andresoviedo/google-drive-ftp-adapter#20]
I am trying to change user and pass to my choice i edited the configuration file but its not working, is there a feature even present to change or its a problem.

**Comment by andresoviedo** [comment]
Hello body. Please check that you have uncommented the configuration file. It means removing the # character from the properties.
Kind regards

**Comment by Androdiver** [comment]
Thanks, now i have changed the user name and pass but how do i sync my all files they were appeared with default conf but now with my custom conf there is only home directory. Actually i am not good with filezilla(newbie), using it but don't know how to sync.
You are awesome, thanks for making such a wonderful tech.

**Comment by VikasRana** [comment]
What do you mean by Sync? It syncs automatically.

It will be helpful if you can copy-paste your confg here removing your personal details like user:pass.

**Comment by andresoviedo** [comment]
@Androdiver do you still have problems using the app? If so, please do what VikasRana says. Copy paste your configuration here removing any personal details. Also, please copy paste the log file to see what's going on
