### ISSUE TITLE
Ability for custom API key? (feature suggestion)

### ISSUE THREAD

**Issue by minhducsun2002** [andresoviedo/google-drive-ftp-adapter#28]
I'm encountering login limit exceeding errors. Can you add the ability for customizing API key?

Many thanks for your project. It really helps me since Drive Sync wasn't available on Linux.

**Comment by andresoviedo** [comment]
You have to generate an API key here:  https://console.developers.google.com

Then change key here:  /src/main/resources/client_secrets.json

**Comment by andresoviedo** [comment]
If you don't want to build the app, just open it with 7zip and change file

**Comment by minhducsun2002** [comment]
Thanks.
