### ISSUE TITLE
Configuration for anonymous user

### ISSUE THREAD

**Issue by TammysHead** [andresoviedo/google-drive-ftp-adapter#31]
Hello,

I would like to have a configuration for the anonymous users. Like the ones for the normal users but for the anonymous one where you don't need user and pass. Thank you 😄 
Changing the name of an account to anonymous and deleting password didn't help because I get this error: "421 Maximum login limit has been reached."

Thanks!

**Comment by andresoviedo** [comment]
Hi @TammysHead  
Please try the latest version. 
You would need to configure the following parameters
If you have any issue please reopen this one
Kind regards

<pre>
# FTP anonymous login
ftp.anonymous.enabled=false
ftp.anonymous.home=
ftp.anonymous.rights=pwd|cd|dir|put|get|rename|delete|mkdir|rmdir|append
</pre>
