### ISSUE TITLE
Install in a command line environment / Docker

### ISSUE THREAD

**Issue by boys3869** [andresoviedo/google-drive-ftp-adapter#40]
Hello everyone,

First of all thank you for this program which is just perfect !!

I would like to use your program in a Docker environment or this one is without GUI ...
Do you have a solution to apply for permission to google account without GUI ?

And even better have you ever thought of deploying your application in a docker so that it is easier to use ?

Regards,
boys3869

**Comment by andresoviedo** [comment]
Hi @boys3869 . Thanks for your feedback @Dustify 

You may also deploy the application as a web application.  Please take a look at google-drive-ftp-adapter-online:

https://github.com/andresoviedo/google-drive-ftp-adapter-online
