### ISSUE TITLE
Open ftp from outside local network

### ISSUE THREAD

**Issue by JaySea77** [andresoviedo/google-drive-ftp-adapter#43]
When opening the ftp on localhost it works. When opening the ftp from another computer within my network it works when I use the internal ip-adres.
When I connect from outside my network and forward the port to my computer I can login, but then the connection is refused.
How can I set it up to accept connections from outside my network. Do I need another port to be opened aswell?

**Comment by andresoviedo** [comment]
Hey.  You need to configure access rules in your server firewall / router and in your client network.

There is 2 ways of communicate with FTP. Passive or Active.  Depending on what is your ftp client configuration, you may need to configure one way or the other.

Please take a look to this page so you can understand what you need.

http://slacksite.com/other/ftp.html

Best regards

**Comment by JaySea77** [comment]
After I bound the ip-address it worked. Don’t know why that was needed.

**Comment by JaySea77** [comment]
I have a new router and want to keep the forwarded ports to a minium.
When I connect from outside my network it does open the ftp, but doesn't do a diretory listing. It just hangs. What other ports should be forwarded?

**Comment by andresoviedo** [comment]
Hi.  If you want to use the app in different networks, please read this.

https://slacksite.com/other/ftp.html
