### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by TobiasDeBruijn** [andresoviedo/google-drive-ftp-adapter#44]
During the setup of GDFA, it tells me to go to the Google link, which I do, I follow the instructions from Google, after which it takes me to localhost:something/something, I change 'localhost' to the PC's IP its running on, then I get an error from Google saying that the site can't be reached.

Why change localhost to the PCs IP? Because the server I want GDFA running, runs Ubuntu 18.04 LTS Server, meaning it doesn't have a browser. 

Any way to fix this or am I doing something wrong?

**Comment by andresoviedo** [comment]
Hello body.  You don't have to do anything. The message you see is Informational only. 
Just connect your ftp client to the adapter 
Please read the instructions on README file. If you have any issue update this thread. 
Kind regards

**Comment by TheDutchMC04** [comment]
Followed all the instructions as stated in the README file, when connecting to the FTP server this is what I get: 
`$ ftp localhost 1821
ftp: connect to address ::1: Connection refused
Trying 127.0.0.1...
ftp: connect: Connection refused
ftp>
`
